service_name: elastic
# 服务端口
port: 8001
# 运行环境
env: prod
# 是否调试模式,调试模式会输出详细的错误信息等
debug: false
# 服务版本
version: 1.0.0
jwt_secret: eyJ0eXAiOiJKLCJhbGciOiJIUzI1N
kafka_broker: 127.0.0.1:9092
#yapi配置
yapi:
  enable: false
  url:
  token:
  cate_id: 0
database:
  # 数据库-主库
  driver: mysql
  #如果不配置就不连接
  #dsn: root:123456@(127.0.0.1)/megin?charset=utf8&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 50
redis:
  addr: 127.0.0.1:6379
  password: ''
  prefix: ''
# rpcx配置
rpcx:
  enable: false
  network: tcp
  listen: 127.0.0.1:8010
  #支持consul
  discovery_addrs:
    - 127.0.0.1:8500